# Generated by Django 5.2.1 on 2025-06-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('ocupada', models.BooleanField(default=False)),
                ('tipo_cliente', models.CharField(choices=[('avulso', 'Avulso'), ('mensalista', 'Mensalista')], default='avulso', max_length=10)),
                ('cliente_mensalista', models.ForeignKey(blank=True, help_text='Cliente associado se a vaga for de um mensalista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas', to='clientes.mensalista')),
            ],
        ),
    ]
