# Generated by Django 5.2.1 on 2025-07-02 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_vaga_entrada_vaga_saida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='vaga',
            name='saida',
        ),
        migrations.CreateModel(
            name='EntradaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.vaga')),
            ],
        ),
    ]
