# Generated by Django 5.2.1 on 2025-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_prevista',
            field=models.DateField(),
        ),
    ]
