# Generated by Django 5.2.1 on 2025-06-25 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoplano',
            name='mensalista',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.mensalista'),
        ),
    ]
